# Generated by Django 3.2.4 on 2021-06-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('owner', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.customer', verbose_name='owner')),
            ],
        ),
    ]
