# Generated by Django 3.2.4 on 2021-07-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210702_2336'),
        ('pets', '0002_alter_pets_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
