# Generated by Django 3.2.4 on 2021-07-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pets_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='added_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
