# Generated by Django 3.2.4 on 2021-07-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pets_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
