# Generated by Django 3.2.4 on 2021-07-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_added_by'),
        ('pets', '0008_alter_pets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='accounts.customer'),
        ),
    ]
