# Generated by Django 3.2.4 on 2021-07-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_pets_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='id',
            new_name='pet_id',
        ),
    ]
