# Generated by Django 3.2.4 on 2021-07-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_rename_id_pets_pet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='pet_id',
            new_name='id',
        ),
    ]
