# Generated by Django 3.2.4 on 2021-08-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_auto_20210811_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_description', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_image', models.ImageField(default='no_blog_images.jpeg', upload_to='blog_images')),
                ('blog_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='accounts.admin')),
            ],
        ),
    ]
