# Generated by Django 3.2.4 on 2021-08-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210811_1910'),
        ('blogs', '0004_auto_20210812_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='illness_uploader',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='accounts.admin'),
        ),
    ]
