# Generated by Django 3.2.4 on 2021-07-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(default='default_image.png', upload_to='admin_profile_pictures'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='default_image.png', upload_to='customer_profile_pictures'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(default='default_image.png', upload_to='staff_profile_pictures'),
        ),
    ]
