# Generated by Django 3.2.4 on 2021-07-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210713_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
