# Generated by Django 3.2.4 on 2021-07-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_admin_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
