# Generated by Django 3.2.4 on 2021-08-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210806_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
    ]
