# Generated by Django 3.2.4 on 2021-08-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_auto_20210811_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Approve'), (2, 'Declined')], null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='accounts.customer')),
            ],
        ),
    ]
