# Generated by Django 3.2.4 on 2021-08-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_date_appointment_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.CharField(max_length=255),
        ),
    ]
