# Generated by Django 3.2.4 on 2021-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='new_schedule',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Approve'), (2, 'ReScheduled'), (3, 'Declined')], null=True),
        ),
    ]
