# Generated by Django 3.2.4 on 2021-08-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20210827_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='new_schedule',
            new_name='old_schedule',
        ),
    ]
