# Generated by Django 3.2.4 on 2021-08-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_rename_new_schedule_appointment_old_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Approved'), (2, 'ReScheduled'), (3, 'Declined')], null=True),
        ),
    ]
